DependencyInjection/Configuration.php, DependencyInjection/GuzzleExtension.php, README.md, Tests/DependencyInjection/ConfigurationTest.php, composer.json
Hi! First of all, thanks for the great bundle.
Since there was no way to provide custom default options when instantiating clients (documentation here: http://guzzle.readthedocs.org/en/latest/request-options.html) I added it. I also added a test for the options array I introduced.
@florianpreusner: can you please consider merging this, or let me know if there's anything you don't like? Thanks!
PS: I had to add some dependencies to your composer.json which are in fact real dependencies but were missing after a fresh install. Without them I wasn't able to run tests on my machine. I made sure to add them with a non-strict version requirement so it shouldn't cause problems to anyone already using this bundle.
=> Added support for Guzzle client options + configuration test

composer.json
Currently, Symfony 3 is marked as incompatible in the composer.json file. I don't see a reason for this – at least on my machine, the bundle works with 3.0. The toolbar icon is a bit too dark for the new 2.8/3.0 toolbar, though.
Since this bundle keeps us from upgrading to Symfony 3, it would be great if you could tag a Symfony 3.0 compatible release.
=> Allow Symfony 3.0

DependencyInjection/GuzzleExtension.php, Tests/DependencyInjection/Fixtures/FakeClient.php, Tests/DependencyInjection/Fixtures/FakeWsseAuthMiddleware.php, Tests/DependencyInjection/GuzzleExtensionTest.php, composer.json
I created the issue #34 (in german) and here is my code proposal.
please give me feedback that I can work on that pull request.
Sebastian
=> Possibility to overwrite classnames with service container parameters

.travis.yml, Tests/DependencyInjection/GuzzleExtensionTest.php, Tests/Events/PostTransactionEventTest.php, composer.json
| Bug fix?      | [yes]
| New feature?  | [no]
| BC breaks?    | [yes]
| Tests pass?   | [yes]
| Fixed tickets | [#55]
| Doc PR        | []
=> Drop PHP 5.5 support, stick to PHPUnit <= 5.4; #55

Log/Logger.php
| Bug fix?          | yes
| BC breaks?     | no
| Tests pass?     | yes
| License            | MIT
Sometimes when i try to access a page, i get this error : 
`Argument 1 passed to EightPoints\Bundle\GuzzleBundle\Log\LogResponse::__construct() must be an instance of Psr\Http\Message\ResponseInterface, null given, called in /path/to/bundle/GuzzleBundle/Log/Logger.php on line 44`
Refreshing the page does not repeat the error (making it hard to reproduce).
I don't know why this append.
I fixed it by checking not null $context['response'] but it might be interesting to look for root problem.
Does anyone have an idea ?
Thank you.
=> Check context response existence before logging it

.varci.yml
=> VarCI: Added rule to remove invalid label on reopen

Log/LogResponse.php, Tests/Log/LogResponseTest.php
Fixed tickets: #48 
License: MIT
=> Fix $response->getBody()->getContents() returns always empty content #48

Resources/views/profiler.html.twig
Tells the user otherwise.
Fixes #86 
License: MIT
Screenshot of preview when no response available:
=> Check if response exists before showing information

Resources/views/debug.html.twig
* The SVG icon is now correctly aligned
* No green color anymore when calls are made to be compliant with native Symfony's collectors
* Improved errored red status integration
* The old toolbar integration is kept thanks to the profiler_markup_version variable
Before:
After:
License: MIT
References:
* http://symfony.com/blog/new-in-symfony-2-8-redesigned-web-debug-toolbar
* https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md#webprofiler
=> Improve web profiler toolbar v2 integration

DependencyInjection/Configuration.php, Tests/DependencyInjection/ConfigurationTest.php
Guzzle allows both an array or a string as cert parameter 
https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L407
License: MIT
=> Allow cert parameter as array in config

DependencyInjection/GuzzleExtension.php
Not calling the Extension::processConfiguration() method prevents tracking env vars correctly, as spotted in symfony/symfony#24020.
=> Fix configuration processing

DependencyInjection/Configuration.php, DependencyInjection/GuzzleExtension.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/GuzzleExtensionTest.php
License: MIT
Allows you to configure the used class per client. This is esp useful when you use the Auto Wire function in Symfony 3.3.
Simply create a class like this:
```php
<?php
declare(strict_types=1);
namespaceDemoBundle;
use GuzzleHttp\Client;
class PaymentsApiClient extends Client
{
}
```
And then configure your service like this:
```
guzzle:
clients:
payments_api:
class: 'DemoBundle\PaymentsApiClient'
base_url: '%payments_api_endpoint%'
```
Then you can use `PaymentsApiClient` as a dependency of your Guzzle Service
=> Allow clients to have a custom class name

README.md
Fixed tickets: [#51]
License: MIT
I created [cache plugin](https://github.com/gregurco/GuzzleBundleCachePlugin) requested in #51
=> Add cache plugin to readme

src/DataCollector/HttpDataCollector.php, tests/DataCollector/HttpDataCollectorTest.php
Fixed tickets: [#141]
License: MIT
=> Add reset method to HttpDataCollector. Required in symfony >= 3.4

README.md, src/DependencyInjection/Configuration.php, tests/DependencyInjection/ConfigurationTest.php, tests/DependencyInjection/EightPointsGuzzleExtensionTest.php
Fixed tickets: [#97]
License: MIT
---
**Added options:**
- allow_redirects - bool or array
- form_params - array
- multipart - array
- sink - string
**Modified options:**
- base_url - string (was boolean, string, integer, float and null)
- auth - string or array (was array only)
- query - string or array (was boolean, string, integer, float and null)
- connect_timeout - float and int (was boolean, string, integer, float and null)
- decode_content - string and bool (was bool) (Note: string in case of decoding, ex: gzip)
- delay - float and int (was boolean, string, integer, float and null)
- expect - bool or int (was boolean, string, integer, float and null)
- ssl_key - string or array with two elements (was boolean, string, integer, float and null)
- stream - bool (was bool or string)
- …
=> Add options and improve existent

src/DependencyInjection/EightPointsGuzzleExtension.php
License: MIT
Allow the use of `HandlerStack::before($name,...)` and `HandlerStack::after($name,...)`
=> [FIX] Add names to middlewares

src/DataCollector/HttpDataCollector.php, src/DependencyInjection/Configuration.php, src/Log/Logger.php, tests/DataCollector/HttpDataCollectorTest.php, tests/DependencyInjection/ConfigurationTest.php, tests/Log/LoggerTest.php
License: MIT
What I did:
- Validate that form_params and multipart can't be used at the same time
- HttpDataCollector::getErrorCount method (there was TODO)
- Improve annotation for logger
- Tests for invalid options and HttpDataCollector::getErrorCount
=> Config and HttpDataCollector improvements

src/DependencyInjection/EightPointsGuzzleExtension.php, src/Resources/config/services.xml, tests/DependencyInjection/EightPointsGuzzleExtensionTest.php
Fixed tickets: [#72]
License: MIT
@florianpreusner so, if logging in configuration is false, then logger, data collector, formatter and log middleware are not defined at all and visa versa. I also wrote tests for these cases :slightly_smiling_face:
=> Deactivate logger/data collector/formatter/log middleware if logging is false

src/Events/PostTransactionEvent.php
Found this exception:
```
Type error: Return value of EightPoints\Bundle\GuzzleBundle\Events\PostTransactionEvent::getTransaction() must be an instance of Psr\Http\Message\ResponseInterface, null returned
```
Checked the code and the issue is the strict return type. Cannot use ` : ?ResponseInterface` because this project also supports PHP 7.0
=> PostTransactionEvent > Remove strict return type to allow null

README.md, composer.json
| Fixed tickets    | #172 
What I did:
- added `assets:install` command in readme, because sometimes this command is not performed automatically and we should provide information about that.
- added `symfony/framework-bundle` in dependencies, because there are some features that bundle uses. For example `assets` function for this is defined there and also command `assets:install`. And as I see, many bundles are dependent on this package.
- removed `symfony/dependency-injection`, `symfony/event-dispatcher`, `symfony/http-kernel` and `symfony/config` because these packages are provided by …
=> Review dependencies

src/DependencyInjection/Configuration.php, tests/DependencyInjection/ConfigurationTest.php
This PR adds `read_timeout` option for guzzle client and allows using environment variables for `connect_timeout`, `read_timeout` and `timeout` settings.
=> Allow to use environment variables for timeouts

src/Twig/Extension/DebugExtension.php
| Fixed tickets    | []
In twig/twig 1.x `Twig_ExtensionInterface` declares `getName` which the current `DebugExtension` is missing.
=> Fix twig extension incompatibility

DependencyInjection/Configuration.php
| Tests pass       | unknown
Pulled changes from the newest version to v6 allowing auth headers to be a string or an array.
=> Add auth configuration to v6 branch in configuration

README.md, src/Resources/doc/redefine-client-class.md
| Fixed tickets    | #181
@florianpreusner I created separate page for this article not not to inflate the main readme. I think next doc articles will do in the same way. To separate them how symfony does with official documentation. What do you think? 
Preview: https://github.com/gregurco/EightPointsGuzzleBundle/blob/doc_redefine_client/src/Resources/doc/redefine-client-class.md :slightly_smiling_face:
=> Doc: how to redefine client class

.travis.yml, README.md, Resources/config/services.xml, Resources/views/debug.html.twig, composer.json
| Fixed tickets    | #199 
The staff related to calling of templates really was changed in SF3.2. I did changes and I guess we have next cases:
- PHP 5, SF 3.1 -> Guzzle Bundle v6.2.0
- PHP 5, SF 3.2 -> Guzzle Bundle v6.2.1 (new release with this fix)
- PHP 7, SF 3.2 -> Guzzle Bundle v7
=>  Fix rendering of templates in v6 and SF >= 3.2

README.md, src/Resources/doc/disable-exception-on-http-error.md
| Fixed tickets    | #204 
See how it looks like: https://github.com/gregurco/EightPointsGuzzleBundle/blob/disable_exception_on_http_error_doc/src/Resources/doc/disable-exception-on-http-error.md
=> [DOC] Disable throwing exceptions on HTTP errors

README.md, src/Resources/doc/configuration-reference.md
It's good practice to have one article page with full configuration reference and on the main page (readme.md) to keep just the most used configuration parameters.
See docs: https://github.com/gregurco/EightPointsGuzzleBundle/blob/configuration_reference/src/Resources/doc/configuration-reference.md
Example:
[FOSRestBundle](https://symfony.com/doc/current/bundles/FOSRestBundle/configuration-reference.html)
[FOSUserBundle](https://symfony.com/doc/current/bundles/FOSUserBundle/configuration_reference.html)
[DoctrineBundle](https://symfony.com/doc/current/bundles/DoctrineBundle/ …
=> Add Configuration Reference

src/DependencyInjection/EightPointsGuzzleExtension.php
=> Non public profiler creates error in SF 2.8

.travis.yml, CONTRIBUTING.md, composer.json, src/DataCollector/HttpDataCollector.php, tests/DataCollector/HttpDataCollectorTest.php
What was changed:
- Replace `hpunit/phpunit` with `symfony/phpunit-bridge` - it will give us additional information during the tests. For example when some deprecations appeared.
- Write test for data collector with slow requests
- Improve travis build - added validation of composer.json, etc.
=> [Tests] General improvement (symfony/phpunit-bridge, travis and new tests)

phpunit.xml.dist
From symfony documentation (https://symfony.com/doc/current/components/phpunit_bridge.html):
> By using SYMFONY_DEPRECATIONS_HELPER=max[self]=0, deprecations that are triggered outside the vendors directory will be accounted for seperately, while deprecations triggered from a library inside it will not (unless you reach 999999 of these), giving you the best of both worlds.
=> Allow vendors deprecations in tests

composer.json, src/Log/LogMessage.php, src/Log/Logger.php, src/Resources/views/profiler.html.twig, tests/Log/LoggerTest.php
| Fixed tickets    | #266 
Now you can run request out of Symfony's context.
**Note:** It does not require `namshi/cuzzle` vendor, but the curl command will appear only if you have it installed, added to the suggested vendors.
=> Print Curl command for debugging purposes

src/DependencyInjection/Configuration.php, src/DependencyInjection/EightPointsGuzzleExtension.php, src/EightPointsGuzzleBundle.php, src/PluginInterface.php, src/Resources/doc/how-to-create-a-single-file-plugin.md, tests/DependencyInjection/EightPointsGuzzleExtensionTest.php, tests/EightPointsGuzzleBundleTest.php
| BC breaks        | yes
| Fixed tickets    | #178
@florianpreusner what do you think about `PluginInterface` instead of long `EightPointsGuzzleBundlePluginInterface`?
=> Rename EightPointsGuzzleBundlePlugin to follow PSR

src/DependencyInjection/Compiler/EventHandlerCompilerPass.php, src/Events/GuzzleEventListenerInterface.php, src/Events/GuzzleEvents.php, src/Middleware/EventDispatchMiddleware.php, tests/DependencyInjection/Compiler/EventHandlerCompilerPassTest.php, tests/Middleware/EventDispatchMiddlewareTest.php, tests/Middleware/Logger.php, tests/Middleware/SymfonyLogMiddlewareTest.php, tests/Twig/Extension/DebugExtensionTest.php
| Deprecations     | yes
| Fixed tickets    | N/A
PR to add functionality introduced in #284, but based against version 7 of this bundle, including deprecation notices.
=> Split events v7

UPGRADE.md
=> [Upgrade] Add info about upgrading From 7.x to 8.0

src/PluginInterface.php
| Fixed tickets    | #297
Interface should be compatible with types from here: https://github.com/symfony/http-kernel/blob/v5.0.4/Bundle/Bundle.php#L37
=> Fix compatibility with HTTP Kernel bundle type hints

README.md, src/DataCollector/HttpDataCollector.php, src/DependencyInjection/Configuration.php, src/DependencyInjection/EightPointsGuzzleExtension.php, src/Log/LogResponse.php, src/Log/Logger.php, src/Resources/doc/configuration-reference.md, tests/DataCollector/HttpDataCollectorTest.php, tests/DependencyInjection/ConfigurationTest.php, tests/DependencyInjection/EightPointsGuzzleExtensionTest.php, tests/Log/LogResponseTest.php, tests/Log/LoggerTest.php, tests/Middleware/RequestTimeMiddlewareTest.php
| Fixed tickets    | related to https://github.com/8p/EightPointsGuzzleBundle/issues/48 https://github.com/8p/EightPointsGuzzleBundle/issues/32
This PR allows to enable/disable logging on a specific client, mainly because the stream rewinding still does not work on particular cases (continuous event streaming as example).
=> Allow to enable/disable logging on a specific client

src/DependencyInjection/EightPointsGuzzleExtension.php, src/Resources/doc/autowiring-clients.md, tests/DependencyInjection/EightPointsGuzzleExtensionTest.php
| Fixed tickets    | --
Since Symfony 4.2, it is possible to create [service aliases by class name and attribute](https://symfony.com/blog/new-in-symfony-4-2-autowiring-by-type-and-name). Inspired by the feature to [auto-wire specific monolog channels](https://github.com/symfony/monolog-bundle/pull/315) I have created this pull request to make it easier to auto-wire Guzzle-clients.
=> Added service aliases to allow easier autowiring

src/Resources/doc/intercept-request-and-response.md
| Fixed tickets    | Documentation fix
Implementing this into a new project and realized there's a minor fix in the documentation required for the interceptor.
=> Fixed a very minor typo in the Intercept Request/Response documentation

src/Resources/views/main.css.twig
=> #295 - Support dark mode in profiler

composer.json, src/Middleware/EventDispatchMiddleware.php, src/Middleware/LogMiddleware.php, src/Middleware/ProfileMiddleware.php, src/Middleware/SymfonyLogMiddleware.php
| Fixed tickets    | #325 and #327
=> Fixed guzzle version constraints and avoid old promises function API

src/DataCollector/DataCollectorSymfonyCompatibilityTrait.php, src/DataCollector/HttpDataCollector.php
| Bug fix          |no
```
Implicitly marking parameter $foo as nullable is deprecated, the explicit nullable type must be used instead
```
=> PHP 8.4 deprecations

README.md
The key must be lowercase version of CURLOPT_SSLVERSION without the CURLOPT_. Also the `!php/const:CURL_HTTP_VERSION_1_0` syntax was invalid (shouldn't have colon after const)
| Bug fix          | /no
=> Fix curl options docs
