8p/EightPointsGuzzleBundle

DependencyInjection/Compiler/EventHandlerCompilerPass.php, DependencyInjection/GuzzleExtension.php, Events/GuzzleEventListener.php, Events/GuzzleEventListenerInterface.php, Events/GuzzleEvents.php, Events/PostTransactionEvent.php, Events/PreTransactionEvent.php, GuzzleBundle.php, Middleware/EventDispatchMiddleware.php, README.md, Resources/config/services.xml
This address #21, it implements an event dispatch middleware that will dispatch a pre-transaction as well as a post-transaction event.  This allows users to implement their own middleware as they need.
=> Event handler

README.md
Updated the Readme to try and make the events more understandable.
=> Update events documentation

DependencyInjection/GuzzleExtension.php
| Bug fix?      | [yes]
| New feature?  | [no]
| BC breaks?    | [no]
| Tests pass?   | []
| Fixed tickets | [https://github.com/8p/GuzzleBundle/issues/39]
| Doc PR        | []
=> Fix Query Option

DataCollector/HttpDataCollector.php, DependencyInjection/Compiler/EventHandlerCompilerPass.php, DependencyInjection/Configuration.php, DependencyInjection/GuzzleExtension.php, Events/GuzzleEventListenerInterface.php, Events/GuzzleEvents.php, Events/PostTransactionEvent.php, Events/PreTransactionEvent.php, GuzzleBundle.php, Log/LogGroup.php, Log/LogMessage.php, Log/LogRequest.php, Log/LogResponse.php, Log/Logger.php, Middleware/EventDispatchMiddleware.php, Middleware/LogMiddleware.php, Middleware/RequestHeaderMiddleware.php, Tests/DataCollector/HttpDataCollectorTest.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/Fixtures/FakeClient.php, Tests/DependencyInjection/Fixtures/FakeWsseAuthMiddleware.php, Tests/DependencyInjection/GuzzleExtensionTest.php, Tests/Events/PostTransactionEventTest.php, Tests/Events/PreTransactionEventTest.php, Tests/Log/LogGroupTest.php, Tests/Log/LogMessageTest.php, Tests/Log/LogRequestTest.php, Tests/Log/LogResponseTest.php, Tests/Log/LoggerTest.php, Tests/Middleware/RequestHeaderMiddlewareTest.php
| Bug fix?      | [no]
| New feature?  | [no]
| BC breaks?    | [no]
| Tests pass?   | [yes]
| Fixed tickets | []
| Doc PR        | []
=> PSR-2 Standard, Removed Redundant Comments

README.md
| Bug fix?      | [no]
| New feature?  | [no]
| BC breaks?    | [no]
| Tests pass?   | [no]
=> Added note about class from guzzle.client.*

DependencyInjection/Configuration.php, DependencyInjection/GuzzleExtension.php, README.md, Tests/DependencyInjection/ConfigurationTest.php
| Bug fix?      | [no]
| New feature?  | [yes]
| BC breaks?    | [no]
| Tests pass?   | [yes, hopefully 🌴 ]
| Fixed tickets | [#45]
| Doc PR        | []
=> WSSE CreatedAt Time Expression

DataCollector/HttpDataCollector.php, Log/LogGroup.php, Tests/Log/LogGroupTest.php
=> Add addMessages method to LogGroup and use in HttpDataCollector

Log/LogRequest.php, Log/LogResponse.php
=> Rewind to previous position after logging request & response body

DataCollector/HttpDataCollector.php, Log/LogGroup.php, Tests/Log/LogGroupTest.php
=> Add addMessages method to LogGroup and use in HttpDataCollector (master)

README.md
=> README.md: fixed version eye id for dependency check

Log/LogRequest.php
| Deprecations? |no
| Fixed tickets |
=> fixed Fatal error: Call to a member function isSeekable() on null

.varci.yml
| Bug fix?      | no
| New feature?  | yes
| Fixed tickets |
=> VarCI Integration

.github/PULL_REQUEST_TEMPLATE.md
=> Improve Github PR Template

DataCollector/HttpDataCollector.php, DependencyInjection/GuzzleExtension.php, Log/DevNullLogger.php, Log/Logger.php, Log/LoggerInterface.php, Middleware/LogMiddleware.php, Tests/Log/LoggerTest.php
=> if you cannot log use DevNull Logger

.varci.yml, README.md
=> Removed VarCI auto-merge; added logging info to README.md

CONTRIBUTING.md, README.md
=> README Cosmetics

DependencyInjection/Configuration.php, DependencyInjection/GuzzleExtension.php
Fixed tickets: #82 
License: MIT
=> Fix: Add headers in options (config) to client arguments

Resources/views/debug.html.twig
Fixes #85 
License: MIT
Inspired from this: https://github.com/symfony/symfony/blob/61a67ecc5a04c0ef950d98042141db243f07865f/src/Symfony/Bundle/DebugBundle/Resources/views/Profiler/dump.html.twig#L4
=> No icon when no call

.idea/php.xml, README.md
=> README Cleanup

.travis.yml
Fixed PR: https://github.com/8p/GuzzleBundle/pull/94 
License: MIT
=> Hotfix: Travis PHPUnit Executable

Middleware/EventDispatchMiddleware.php
License: MIT
Default Exception class added.
=> Handle error responses with exception class

DependencyInjection/Configuration.php, Tests/DependencyInjection/ConfigurationTest.php
Fixed tickets: #97 
License: MIT
=> Added option "proxy" (#97)

DependencyInjection/Configuration.php, DependencyInjection/GuzzleExtension.php, Tests/DependencyInjection/ConfigurationTest.php
Fixed tickets: [#101 - Params in header]
License: MIT
=> Headers configuration that allow underscores

Middleware/EventDispatchMiddleware.php
=> Fixing preTransaction event replace request object.

Log/LogGroup.php, Tests/Log/LogGroupTest.php, Tests/Log/LogMessageTest.php, Tests/Log/LogRequestTest.php, Tests/Middleware/EventDispatchMiddlewareTest.php, Tests/Middleware/FlexiblePromise.php, Tests/Middleware/LogMiddlewareTest.php
Coverage increased from 58.96% to 77.92%
License: MIT
=> Add tests and improve coverage

DependencyInjection/GuzzleExtension.php, Tests/DependencyInjection/GuzzleExtensionTest.php
Fixed tickets: [#113]
License: MIT
=> Add getConfiguration method in GuzzleExtension

Middleware/EventDispatchMiddleware.php
See also PR https://github.com/8p/GuzzleBundle/pull/119
Fixed tickets:
License: MIT
=> Fixing postTransaction event replace request object

README.md, src/DependencyInjection/Configuration.php, tests/DependencyInjection/ConfigurationTest.php
License: MIT
@florianpreusner I removed header, that are not in options.
=> Remove deprecated header

README.md
=> README.md: fixed broken external links, added/changed plugin section

README.md, src/DependencyInjection/Configuration.php, tests/DependencyInjection/ConfigurationTest.php
Fixed tickets: [#109]
Duplicates PR: [#103]
License: MIT
**TODO:**
IMPORTANT: don't merge. It's not finished PR.
=> Allow to configure curl options

README.md
Fixed tickets: [#58]
License: MIT
=> Add gregurco/GuzzleBundleOAuth2Plugin to readme

README.md
=> [doc] Be consistent with header in options array

README.md, UPGRADE.md
Remove versionEye from readme.
Fixed tickets: [#149]
License: MIT
=> Create UPGRADE.md with guide for migration from 6.x to 7.0

README.md, src/DataCollector/HttpDataCollector.php, src/DependencyInjection/Configuration.php, src/Log/LogRequest.php, src/Log/Logger.php
=> Add Scrutinizer CI

src/DataCollector/HttpDataCollector.php, src/DependencyInjection/EightPointsGuzzleExtension.php, src/Middleware/RequestTimeMiddleware.php, src/Resources/config/services.xml, tests/DataCollector/HttpDataCollectorTest.php, tests/DependencyInjection/EightPointsGuzzleExtensionTest.php, tests/Middleware/RequestTimeMiddlewareTest.php
License: MIT
Proof :slightly_smiling_face: : 
Todo:
=> Calculate all requests time

CONTRIBUTING.md, src/DataCollector/HttpDataCollector.php, src/DependencyInjection/Compiler/EventHandlerCompilerPass.php, src/DependencyInjection/Configuration.php, src/DependencyInjection/EightPointsGuzzleExtension.php, src/EightPointsGuzzleBundle.php, src/EightPointsGuzzleBundlePlugin.php, src/Events/GuzzleEventListenerInterface.php, src/Events/PostTransactionEvent.php, src/Events/PreTransactionEvent.php, src/Log/DevNullLogger.php, src/Log/LogGroup.php, src/Log/LogMessage.php, src/Log/LogRequest.php, src/Log/LogResponse.php, src/Log/Logger.php, src/Log/LoggerInterface.php, src/Middleware/EventDispatchMiddleware.php, src/Middleware/LogMiddleware.php, tests/DataCollector/HttpDataCollectorTest.php, tests/DependencyInjection/EightPointsGuzzleExtensionTest.php, tests/Log/LogRequestTest.php, tests/Log/LogResponseTest.php, tests/Log/LoggerTest.php, tests/Middleware/EventDispatchMiddlewareTest.php, tests/Middleware/LogMiddlewareTest.php
=> Fix annotations

README.md
=> Add installation guide through flex to readme

tests/DependencyInjection/EightPointsGuzzleExtensionTest.php
=> Add tests for overriding classes

.travis.yml
=> PHP 7.2 and Symfony 3.4/4.0 are released!

README.md, src/DependencyInjection/EightPointsGuzzleExtension.php, src/Middleware/SymfonyLogMiddleware.php, src/Resources/config/services.xml, tests/DependencyInjection/EightPointsGuzzleExtensionTest.php, tests/Middleware/SymfonyLogMiddlewareTest.php
Fixed tickets: [#99]
License: MIT
=> Log requests into symfony default logger

composer.json, src/DependencyInjection/EightPointsGuzzleExtension.php, tests/DependencyInjection/EightPointsGuzzleExtensionTest.php
Fixed tickets: [#20]
License: MIT
=> Add twig in dependencies and define explicitly twig debug extension

src/DependencyInjection/EightPointsGuzzleExtension.php, tests/DependencyInjection/EightPointsGuzzleExtensionTest.php
Fixed tickets: [#165]
License: MIT
=> Fast-fix for twig extension and request time middleware

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
License: MIT
Inspired from: https://github.com/symfony/symfony/tree/master/.github
=> Add template for issue and improve template for pull request

.travis.yml, composer.json, src/DependencyInjection/EightPointsGuzzleExtension.php, src/Resources/views/profiler.html.twig, src/Twig/Extension/DebugExtension.php, tests/DependencyInjection/EightPointsGuzzleExtensionTest.php, tests/Twig/Extension/DebugExtensionTest.php
| Fixed tickets    | #20 #165 
Todo:
=> Create own function for dump-ing in profiler

composer.json
=> Update Composer Description

README.md
| Bug fix          |no
| New feature      |no
| BC breaks        |no
| Deprecations     |no
Still need to write some README file on those plugins to explain what they do...
=> [UPDATE] Add plugins

.travis.yml, src/Resources/public/css/main.css
=> [Profiler] Patch request style

README.md, src/Resources/doc/intercept-request-and-response.md
See how it looks like: https://github.com/gregurco/EightPointsGuzzleBundle/blob/interceptor_doc/src/Resources/doc/intercept-request-and-response.md
=> [DOC] Intercept request and response

README.md, src/Resources/doc/autowiring-clients.md, src/Resources/doc/intercept-request-and-response.md
| Fixed tickets    | #191 
See the page here: https://github.com/gregurco/EightPointsGuzzleBundle/blob/autowire_docs/src/Resources/doc/autowiring-clients.md
=> Autowire docs

.gitignore, CONTRIBUTING.md, infection.json.dist
=> Some testing description is added to the contributing guide.

.gitattributes, src/DataCollector/HttpDataCollector.php, src/Middleware/RequestTimeMiddleware.php, tests/DataCollector/HttpDataCollectorTest.php, tests/Log/LogMessageTest.php, tests/Log/LoggerTest.php, tests/Middleware/RequestTimeMiddlewareTest.php, tests/Twig/Extension/DebugExtensionTest.php
I'm just trying to improve my testing skills : )
Do my changes make sense ?
=> Infection PHP is added, also strict types enabled. Minor improvement.

README.md, src/DependencyInjection/Configuration.php, src/DependencyInjection/EightPointsGuzzleExtension.php, tests/DependencyInjection/ConfigurationTest.php
=> Add option to create lazy clients

src/DependencyInjection/Configuration.php, src/DependencyInjection/EightPointsGuzzleExtension.php, src/Middleware/ProfileMiddleware.php, src/Resources/config/services.xml, tests/DependencyInjection/ConfigurationTest.php, tests/DependencyInjection/EightPointsGuzzleExtensionTest.php, tests/Middleware/ProfileMiddlewareTest.php
=> [Profiler] Add request profiling to performance metrics

README.md, src/DependencyInjection/Configuration.php, src/DependencyInjection/EightPointsGuzzleExtension.php, tests/DependencyInjection/ConfigurationTest.php, tests/DependencyInjection/EightPointsGuzzleExtensionTest.php
=> Add the option to use a custom handler class such as Guzzle MockHandler

README.md, src/DataCollector/HttpDataCollector.php, src/DependencyInjection/Configuration.php, src/DependencyInjection/EightPointsGuzzleExtension.php, src/Resources/views/debug.html.twig, tests/DataCollector/HttpDataCollectorTest.php, tests/DependencyInjection/ConfigurationTest.php
=> Show profiler in yellow when a response is slow

tests/DependencyInjection/EightPointsGuzzleExtensionTest.php
=> Covered with tests issue 229

README.md, src/DependencyInjection/EightPointsGuzzleExtension.php, src/Resources/doc/environment-variables-integration.md
| Fixed tickets    | #220
See doc here: https://github.com/gregurco/EightPointsGuzzleBundle/blob/doc_env_variables/src/Resources/doc/environment-variables-integration.md
=> [Guide] How to use environment variables with bundle

src/DependencyInjection/Configuration.php
| Fixed tickets    | N/A
Creating a new TreeBuilder without root node information is
deprecated since Symfony 4.2.
See https://github.com/symfony/symfony/blob/master/UPGRADE-4.2.md#config
=> Supply name for new TreeBuilder instead of calling root method

.travis.yml, phpunit.xml.dist
=> [Travis] Add support of Symfony 4.2

composer.json, src/DependencyInjection/Configuration.php, tests/DependencyInjection/EightPointsGuzzleExtensionTest.php, tests/Fixtures/config/test_api_1.yaml, tests/Fixtures/config/test_api_2.yaml
=> Fix issue with merging of bundle configuration

src/DependencyInjection/EightPointsGuzzleExtension.php
=> Allow handler to be available in the private container

src/DependencyInjection/EightPointsGuzzleExtension.php, tests/DependencyInjection/EightPointsGuzzleExtensionTest.php
=> Fix issue #258 - add ability to use clients without plugins

.travis.yml
=> Add Symfony 4.3 to travis build

README.md
| Bug fix          | yes/no
| New feature      | yes/no
| BC breaks        | yes/no
| Deprecations     | yes/no
| Tests pass       | yes/no
| Fixed tickets    | [comma-separated list of tickets fixed by the PR, if any]
=> add retry plugin to readme

src/Events/Event.php, src/Events/PostTransactionEvent.php, src/Events/PreTransactionEvent.php, src/Middleware/EventDispatchMiddleware.php, src/Twig/Extension/DebugExtension.php, tests/DataCollector/HttpDataCollectorTest.php
| Deprecations     | yes
| Fixed tickets    | #261
Inspired with solution from https://github.com/gesdinet/JWTRefreshTokenBundle :slightly_smiling_face:
=> Adjust code for deprecation messages appeared in SF 4.3 and Twig

src/DependencyInjection/EightPointsGuzzleExtension.php, src/Middleware/ProfileMiddleware.php, src/Middleware/RequestTimeMiddleware.php
| Fixed tickets    | #253
After that PR we can create last tag for v7 and start working on v8.
=> Move logging middlewares before plugins initialization

src/Resources/views/debug.html.twig
=> [Profiler] Change color in left menu based on http status code

src/Resources/doc/intercept-request-and-response.md
=> [Documentation] Rename subscriber to listener

.travis.yml, composer.json, src/DataCollector/DataCollectorSymfonyCompatibilityTrait.php, src/DataCollector/HttpDataCollector.php, src/Twig/Extension/DebugExtension.php, tests/DataCollector/HttpDataCollectorTest.php, tests/Middleware/Logger.php, tests/Middleware/RequestTimeMiddlewareTest.php, tests/Middleware/SymfonyLogMiddlewareTest.php, tests/Twig/Extension/DebugExtensionTest.php
=> Add support of Symfony 5.x

src/Resources/views/debug.html.twig
=> Fix namespace error in profiler

.travis.yml
=> Upgrade versions of symfony in travis config

.travis.yml
=> Upgrade travis config for v7

src/Middleware/EventDispatchMiddleware.php
=> Process Throwable reason without useless TypeError

.travis.yml, README.md, composer.json, phpunit.xml.dist, src/Log/DevNullLogger.php, src/Log/Logger.php, tests/DataCollector/HttpDataCollectorTest.php, tests/DependencyInjection/EightPointsGuzzleExtensionTest.php, tests/Log/LogRequestTest.php, tests/Log/LogResponseTest.php, tests/Log/LoggerTest.php, tests/Middleware/EventDispatchMiddlewareTest.php, tests/Middleware/RequestTimeMiddlewareTest.php, tests/Twig/Extension/DebugExtensionTest.php
| Tests pass       | no
Allow symfony 6 , psr/log 2|3.
=> Allow symfony 6 

tests/DataCollector/HttpDataCollectorTest.php
=> Fixed `testTotalTime`

src/Middleware/EventDispatchMiddleware.php
=> Replace exception argument by throwable

src/DataCollector/DataCollectorSymfonyCompatibilityTrait.php, src/EightPointsGuzzleBundle.php
=> Fix deprecations (return void)

src/DependencyInjection/EightPointsGuzzleExtension.php
| Deprecations     | yes (fix)
| Fixed tickets    | #340
=> Fix Symfony Extension class deprecation

.github/workflows/phpunit.yml, README.md, tests/DependencyInjection/ConfigurationTest.php
=> Upgrade pipelines version of PHP and Symfony
